class Consts{
optionsStudents = [
    { value: "school ", label: "student's school" },
    { value: "sex", label: "student's sex" },
    { value: "age", label: "student's age" },
    { value: "address", label: "student's home address tyep" },
    { value: "famsize ", label: " family size" },
    { value: "Pstatus", label: "parent's cohabitation status" },
    { value: "Medu", label: "mother's education" },
    { value: "Fedu", label: "father's education" },
    { value: "Mjob ", label: "mother's job" },
    { value: "Fjob", label: "father's job" },
    { value: "reason", label: "student's guardian" },
    { value: "guardian", label: "student's home address tyep" },
    { value: "traveltime ", label: "home to school travel time" },
    { value: "studytime ", label: "weekly study time" },
    { value: "failures ", label: "number of past class failures" },
    { value: "schoolsup", label: "extra educational support" },
    { value: "famsup  ", label: "family educational support" },
    { value: "paid", label: "extra paid classes within the course subject" },
    { value: "activities", label: "extra-curricular activities" },
    { value: "nursery", label: "attended nursery school" },
    { value: "higher  ", label: "wants to take higher education" },
    { value: "internet", label: "Internet access at home" },
    { value: "romantic", label: "with a romantic relationship" },
    { value: "famrel", label: "quality of family relationships" },
    { value: "freetime  ", label: "free time after school" },
    { value: "goout", label: "going out with friends" },
    { value: "Dalc", label: "workday alcohol consumption" },
    { value: "Walc", label: "weekend alcohol consumption" },
    { value: "health", label: "current health status" },
    { value: "absences", label: "number of school absences" },
    { value: "G1", label: "first period grade" },
    { value: "G2", label: "second period grade" },
    { value: "G3 ", label: "final grade" }
]
}